### ISSUE TITLE
Unrecognized option "antares_accessible" under "framework" -symfony 2.2

### ISSUE THREAD

**Issue by 1988gadocansey** [antares993/AccessibleBundle#1]
Boss thanks alot for the awesome bundle but am having configuration error "Unrecognized option "antares_accessible" under "framework" and am using symfony 3.2
framework:
    #esi:             ~
    translator:      { fallbacks: ['%locale%', 'en'] }
    secret:          '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets: ~
    property_access:
        magic_call: true
    antares_accessible:
        cache.enable: true # default: false
        constraints_validation.enable: false # default: true
        constraints_validation.validate_initialize_values: true # default: %kernel.debug%

**Comment by antarestupin** [comment]
Hello, since I don't remind when, Symfony's YAML parser does not allow anymore to use a dot to access nested values, so for example `cache.enable: true` should be replaced by `cache: { enable: true }`, so you should set the configuration like this:

```yaml
antares_accessible:
    cache:
        enable: true
    constraints_validation:
        enable: false
        validate_initialize_values: true
```

Note that this configuration is optional, you can skip this step. Also, as you say that the error appears under `framework` and I cannot see the indentation in the code, I'm not sure you put it in the right place so I remind you that `antares_accessible` is to put at root of your configuration.

Anyway thanks for the reporting, I'll update the doc so that this won't reproduce again.
